[Feature] 가이드 텍스트 박스를 추가합니다.
webtoon-today/design-system pull request #50
Opened 2024-07-02 05:19 UTC by DY414

```python
1. 왜 바꿨는지: PR의 목적을 적어주세요.
2. 영향 받을 수 있는 것들: 잠재적으로 이 PR에 의해 영향받을 수 있는 library, stylesheet, 동작방식 등을 적어주세요.
3. QA List: PR이 정상 작동한다면 기대되는 동작/나와선 안되는 동작을 체크리스트로 작성해주세요.
```

# 1. 왜 바꿨는지
- 가이드 텍스트 박스를 추가합니다 ( general, password, pairedVarification ) 

# 2. 영향 받을 수 있는 것들
-

# 3. QA List
- [ ]

2024-07-02 06:18 UTC, 0mini99 reviewed
기존 코드에서 존재하던 문제로 생각되는 부분이지만 컴포넌트를 이관하면서 리펙토링할 수 있을 만한 사항들 리뷰남깁니다~!

2024-07-02 06:18 UTC, 0mini99 commented on packages/input/GuideTextBox/src/GuideTextBoxForPairedVerification.tsx
> +    }
각 가이드 텍스트 컴포넌트에서 guidTextType을 판단하는 로직이 let 변수에 재할당하는 방식으로 구현되어 있어서 재할당을 제거하는 방안으로 util 함수 `getGuideTextType`을 선언하는 방식은 어떨까 합니다

```typescript
// utils
const getGuideTextType = (conditions: {[key in guideTextType]?: boolean}) => {
    if(conditions['required']){
        return 'required';
    }
    if(conditions['success']){
        return 'success';
    }
    if(conditions['fail']){
        return 'fail';
    }
    return 'normal';
}

// L27:35
const guideTextType = 
  forcedGuideTextType || 
  getGuideTextType({
    required: hasClicked && validationStatus === 'undone' && !(isFocused && text.length > 0),
    success: validationStatus === 'success' && secondStepValidationStatus === 'success' && !isFocused
  });
}

2024-07-03 01:15 UTC, 0mini99 reviewed
1. `GuideTextBoxForPairedVerification.tsx`에서 import 구문 수정
2. `getGuideTextType` 함수와 같이 `getButtonStatus` 유틸 함수 작성 제안
3. 컨디션에 따라 className 부여 컨벤션

위 사항에 대해서 코드 리뷰남깁니다!

2024-07-03 01:15 UTC, 0mini99 commented on packages/input/GuideTextBox/src/GuideTextBoxForPairedVerification.tsx
> +    }
이 코드도 컴포넌트 밖에서 getButtonStatus를 정의하여 함수 안에서 getGuideTextType함수를 호출하는 것처럼 사용하는 것은 어떨까요?

`GuideTextBoxForStandAloneVerification.tsx`에서도 buttonStatus를 결정하는 코드가 있어서 제안드립니다

```typescript
const buttonStatus = getButtonStatus({
  inactivated: inactivated_condition
  success: success_condition 
})
```

2024-07-03 01:15 UTC, 0mini99 commented on packages/input/GuideTextBox/src/Function.tsx
> +}
제가 제안드린 방법이지만 이렇게도 될 것 같습니다..!

```typescript
export const getGuideTextType = (conditions: {[key in guideTextType]?: boolean}): guideTextType => {
    Object.entries(conditions).forEach(([key, value]) => {
        if (value) {
            return key;
        }
    });

    return 'normal';
}
```

2024-07-03 01:30 UTC, DY414 commented on packages/input/GuideTextBox/src/GuideTextBox.tsx
> +                <input
배열로 하는게 나은 것 같네요 ~
해당 부분이 너무 길어지는 것 같아 변수로 넣었습니다 ~

2024-07-03 03:23 UTC, DY414 commented on packages/input/GuideTextBox/src/Function.tsx
> +}
forEach는 결과를 반환하지 않아서, map을 사용해 비슷한 방식으로 처리했습니다~

2024-07-03 04:33 UTC, 0mini99 commented on packages/input/GuideTextBox/src/Function.tsx
> +}
conditions에 fail, success, required 를 모두 넘겨줄 때 항상 fail에 대한 컨디션만 검사하게 될 것 같습니다.

로직이 수정되어야 할 것 같아요!

2024-07-03 04:35 UTC, 0mini99 commented on packages/input/GuideTextBox/src/Function.tsx
> +}
그렇네요 내부 로직 수정되야할 것 같습니다..!

2024-07-03 04:57 UTC, 0mini99 commented on packages/input/GuideTextBox/src/Function.tsx
> +}
```suggestion
export const getGuideTextType = (conditions: {[key in guideTextType]?: boolean}) => {
    const foundType = ([ "required", "success", "fail" ] as const).find( type => conditions[type] )
    
    return foundType ??  'normal';
}
```

이렇게 되면 될까요?

2024-07-03 05:04 UTC, 0mini99 approved these changes

2024-07-03 09:36 UTC, sugeul requested changes
현재 사용되는 코드와 완전히 동일한지(스토리만 추가된건지), 아니면 다른부분이 있는지 체크해서 본문에 적어주시기 바랍니다~

2024-07-04 00:20 UTC, closed without merging