[Bugfix][Toast] 메시지가 변하지 않고 toastAlert 함수가 두 번 이상 호출 시 토스트가 보이지 않는 문제 수정합니다.
webtoon-today/design-system pull request #60
Opened 2024-07-09 06:47 UTC by 0mini99

```python
1. 왜 바꿨는지: PR의 목적을 적어주세요.
2. 영향 받을 수 있는 것들: 잠재적으로 이 PR에 의해 영향받을 수 있는 library, stylesheet, 동작방식 등을 적어주세요.
3. QA List: PR이 정상 작동한다면 기대되는 동작/나와선 안되는 동작을 체크리스트로 작성해주세요.
```

# 1. 왜 바꿨는지
- `Toast.tsx`의 useEffect에서 message가 변화할 때 fade-in, fade-out 에니메이션이 발생하여 message가 변하지 않았지만 toastAlert 함수를 호출할 때 토스트가 보이지 않는 문제가 있습니다.
- `css`: `width: 100vw` 대신 `right: 0; left: 0;`을 사용합니다.
- `useToastAlert`를 사용하는 스토리를 추가합니다.

### `RootToast`
일반적인 모달, 다이얼로그 등과 같이 `show`, `onClose` props를 추가합니다.

```tsx
const MyComponent = () => {
  const [show, setShow] = useState(false);
  
  return (
    <div>
      <button onClick={() => setShow(true)}>toast</button>
      <Toast show={show} message={'hello'} onClose={() => setShow(false)}/>
    </div>
)}
```

### `useToastAlert`
- 함수로써 `toastAlert`을 사용하기 위한 외부 인터페이스의 변화는 없습니다.
- `useToastAlert`가 recoil의 atom state를 사용하고 있어 `show`를 멤버에 추가하였습니다.
- `useToastAlert`의 구현에서 함수 호출시 show를 true로 세팅합니다.
- `Toast` 컴포넌트의 onClose 이벤트에 show를 false로 세팅해줍니다.

# 2. 영향 받을 수 있는 것들
-

# 3. QA List
- [ ]

2024-07-10 01:51 UTC, sugeul requested changes
이번 변경사항은 그다지 깔끔하지 않게 느껴지는데요, open과 같은 state를 외부로 꺼내는 것이 특히 좀 아쉽습니다~
만약 동일한 props로 요청하더라도 새로 띄워주는게 의도라면, 더미 props를 하나 넣어서 랜덤값을 주고 dependency로 걸어주면 어떨까 합니다.

2024-07-10 01:51 UTC, sugeul commented on packages/feedback/Toast/src/Toast.tsx
> +    }, [message, timeout, open]);
handleClose가 외부에서 훅으로 생성되었으니 dependencies에 들어가야 할 것 같습니다~!

2024-07-10 01:51 UTC, sugeul commented on packages/feedback/Toast/src/Toast.tsx
> +    }, []);
L40의 clearTimeout이 언마운트시에도 호출되기 때문에 별도의 cleanup은 필요하지 않을 것 같습니다!

2024-07-10 01:56 UTC, 0mini99 commented on packages/feedback/Toast/src/Toast.tsx
> +    }, []);
L40의 clearTimeout은 timeout에 의해서 실행되는 타이머에 대한 함수이고,
해당 라인은 `handleClose` 함수에서 사용하는 `closeTimer`를 지우기 위해서 별도의 useEffect cleanup 함수를 작성하였습니다!

2024-07-10 08:50 UTC, sugeul approved these changes
확인했습니다 감사합니다!

2024-07-11 02:54 UTC, DY414 approved these changes

2024-07-11 02:55 UTC, merged